# Generated by Django 2.0.4 on 2019-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
