# Generated by Django 2.0.4 on 2019-04-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_img2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG2',
        ),
    ]
