# Generated by Django 2.0.4 on 2019-04-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GYS',
        ),
    ]
